class Guitar:
    BANK_NUMBER = 70

    voices = [
        {"name": "Nylon Gtr 1", "voice_number": 1},
        {"name": "Nylon Gtr 2", "voice_number": 2},
        {"name": "Steel Gtr", "voice_number": 3},
        {"name": "Solo Steel", "voice_number": 4},
        {"name": "Steel Away", "voice_number": 5},
        {"name": "12str Gtr", "voice_number": 6},
        {"name": "Jz Gtr Hall", "voice_number": 7},
        {"name": "LetterFrmPat", "voice_number": 8},
        {"name": "JC Strat", "voice_number": 9},
        {"name": "Clear Guitar", "voice_number": 10},
        {"name": "Searing Lead", "voice_number": 11},
        {"name": "Dist Gtr", "voice_number": 12},
        {"name": "Feed Me!", "voice_number": 13},
        {"name": "Blusey OD", "voice_number": 14},
        {"name": "RD Ac.Bass", "voice_number": 15},
        {"name": "RD Upright", "voice_number": 16},
        {"name": "Ac.Upright", "voice_number": 17},
        {"name": "RD Fretless", "voice_number": 18},
        {"name": "Fretless Dry", "voice_number": 19},
        {"name": "Finger Bass", "voice_number": 20},
        {"name": "Pick Bass", "voice_number": 21},
        {"name": "Slap Bass", "voice_number": 22},
        {"name": "MG Bs", "voice_number": 23},
        {"name": "Rubber Bass", "voice_number": 24},
        {"name": "Wonder Bass", "voice_number": 25},
        {"name": "Creamy Bass", "voice_number": 26},
        {"name": "Hefty Bass", "voice_number": 27},
        {"name": "House Bass", "voice_number": 28},
        {"name": "101 Bass", "voice_number": 29},
        {"name": "8VCO MonoSyn", "voice_number": 30}
    ]
